### ISSUE TITLE
Can I use FluentMigrator with .NET Core?

### ISSUE THREAD

**Issue by olafleur** [schambers/fluentmigrator#778] opened 2017-02-24 04:29 UTC
If not, is this support planned ?

**Comment by fubar-coder** [comment] 2017-02-24 06:14
It's not supported yet, but support is definitely planned.

**Comment by eloekset** [comment] 2017-02-24 07:12
@olafleur follow #712

**Comment by reinaldocoelho** [comment] 2017-02-24 12:12
I think we can close this issue and maintain discussion in the #712, right?

**Comment by fubar-coder** [comment] 2017-02-24 12:57
Closed as duplicate of #712

**Closed by fubar-coder** 2017-02-24 12:57 UTC

**Comment by olafleur** [comment] 2017-02-24 15:39
Thanks a lot !
